version: '3.9'

# Configuração específica para produção no VPS
# Use .env para definir as variáveis de ambiente

services:
  backend:
    image: ${IMAGE_NAMESPACE}/sistema-futebol-backend:latest
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "5001:5000"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - sistema-futebol

  frontend:
    image: ${IMAGE_NAMESPACE}/sistema-futebol-frontend:latest
    restart: unless-stopped
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5001}
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      - sistema-futebol

networks:
  sistema-futebol:
    driver: bridge