services:
  postgres:
    image: postgres:15-alpine
    container_name: sistema_futebol_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_futebol_prod
      POSTGRES_USER: sistema_futebol
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1410andrE!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sistema-futebol
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistema_futebol -d sistema_futebol_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: ${IMAGE_NAMESPACE}/sistema-futebol-backend:latest
    container_name: sistema_futebol_backend
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://sistema_futebol:${POSTGRES_PASSWORD:-1410andrE!}@postgres:5432/sistema_futebol_prod
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS}
      PYTHONUNBUFFERED: 1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sistema_futebol_prod
      DB_USER: sistema_futebol
      DB_PASSWORD: ${POSTGRES_PASSWORD:-1410andrE!}
      SKIP_MIGRATIONS: ${SKIP_MIGRATIONS:-false}
      SKIP_SCHEMA_VALIDATION: ${SKIP_SCHEMA_VALIDATION:-false}
      SKIP_HEALTH_CHECK: ${SKIP_HEALTH_CHECK:-false}
    ports:
      - "5001:5000"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sistema-futebol
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
+   logging:
+     driver: json-file
+     options:
+       max-size: "10m"
+       max-file: "3"

  frontend:
    image: ${IMAGE_NAMESPACE}/sistema-futebol-frontend:latest
    container_name: sistema_futebol_frontend
    restart: unless-stopped
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://esporteflowpro.com.br/api}
      NODE_ENV: production
    ports:
      - "8080:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - sistema-futebol
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
+   logging:
+     driver: json-file
+     options:
+       max-size: "10m"
+       max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  sistema-futebol:
    driver: bridge