"""cleanup tmp players table

Revision ID: d5a0b37e5b49
Revises: b97cc35f62e7
Create Date: 2025-10-10 01:29:35.588655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a0b37e5b49'
down_revision = 'b97cc35f62e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropar tabela temporária residual se existir (limpeza de schema)
    op.execute('DROP TABLE IF EXISTS "_alembic_tmp_players"')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recriar tabela temporária minimamente (apenas para simetria)
    op.execute('CREATE TABLE IF NOT EXISTS "_alembic_tmp_players" (id TEXT)')
    # ### end Alembic commands ###
