openapi: 3.0.3
info:
  title: Sistema Futebol API
  version: 0.1.0
  description: API para autenticação, jogadores e períodos mensais.
servers:
  - url: http://localhost:5000/api
    description: Desenvolvimento
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required: [email, password]
    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        monthly_fee:
          type: number
          format: float
    MonthlyPeriod:
      type: object
      properties:
        id:
          type: integer
        month:
          type: integer
        year:
          type: integer
    MonthlyPlayer:
      type: object
      properties:
        id:
          type: integer
        player_id:
          type: integer
        period_id:
          type: integer
        custom_monthly_fee:
          type: number
          format: float
paths:
  /auth/login:
    post:
      summary: Login e obtenção de token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Credenciais inválidas
  /players:
    get:
      summary: Lista jogadores
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de jogadores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '401':
          description: Não autorizado
  /monthly-periods:
    get:
      summary: Lista períodos mensais
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de períodos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MonthlyPeriod'
        '401':
          description: Não autorizado