name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env vars
        run: |
          echo "FLASK_ENV=testing" >> $GITHUB_ENV

      - name: Minimal DB validation
        run: |
          python scripts/validate_db_minimal.py

      - name: Run backend smoke tests
        working-directory: backend
        run: |
          pytest -q -m "not slow" --maxfail=1 --disable-warnings